### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by zimmi** [jhannes/logevents#21]
Hi, I saw your talk at JavaZone, great stuff! One thing from logback that is missing is support for Java Modules (JPMS).

Full support would require adding a `module-info.java` file that is compiled with JDK9+, [logback does this](https://github.com/qos-ch/logback/tree/master/logback-core/src/main/java9). That requires a bit of build system configuration but allows users of logevents to build custom JDK images with `jlink`. The configuration can be simplified by using the [moditect-maven-plugin](https://github.com/moditect/moditect#adding-a-module-descriptor-to-the-project-jar).

As a stopgap, reserving a module name through `Automatic-Module-Name` in `MANIFEST.MF` might be a first step though. Sadly that's not enough for `jlink`, but it at least provides some protection against name clashes in the future. I did that [for another project](https://github.com/PebbleTemplates/pebble/pull/416/files), it's not a lot of code.

About the module name, the [official naming strategy recommendation](http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html) says:

>Strongly recommend that all modules be named according to the reverse Internet domain-name convention. A module's name should correspond to the name of its principal exported API package, which should also follow that convention. If a module does not have such a package, or if for legacy reasons it must have a name that does not correspond to one of its exported packages, then its name should at least start with the reversed form of an Internet domain with which the author is associated.

That seems to be `org.logevents` in this case.

**Comment by jhannes** [comment]
I have been wanting to do this, but don't yet understand the module system 100%. I would love to have your help getting it up and running well.

At the same time as I want to be working will with modules, I want to remain compatible with Java 8.

Related to this: javadoc generation fails with JDK 11+. And for a little used, but very useful embedded https server, I use some restricted packages.

I will look into trying moditect and fixing these issues as the next task for logevents. If you would like to contribute some more information or a pull request, I'd love to have it.

**Comment by zimmi** [comment]
>At the same time as I want to be working will with modules, I want to remain compatible with Java 8.

Right, that should be possible.

>javadoc generation fails with JDK 11+

moditect runs on JDK 8, it shouldn't look at javadoc at all.

>embedded https server

The `com.sun.net.httpserver` package is inside the [jdk.httpserver](https://docs.oracle.com/en/java/javase/12/docs/api/jdk.httpserver/module-summary.html) module, writing a `requires` clause for it should work.

I can't guarantee that I have time to work on this soon, but I'll open a PR if I can.
